### PR TITLE
Don't swap icons if we're the active element

### PR DESCRIPTION
**Pull request by gkatsev**

### CODE REVIEW

**Comment by forbesjo** [comment]
:shaved_ice:

**Comment by misteroneill** [comment]
Is there any chance that the focus could be on a descendant of `this.el()`? Or does that not seem relevant?

**Comment by gkatsev** [comment]
The styles are dependent on the playlist menu item having focus and not a descendant.

**Comment by misteroneill** [comment]
Cool. Then, LGTM!

**Pull request merged**
