### PR TITLE
Updates for VideoJS 5.0

### PR DESCRIPTION
**Pull request by misteroneill**
Brings this plugin up to date with VideoJS 5.0 API changes.

### CODE REVIEW

**Comment by misteroneill** [comment]
Tests are currently failing because they depend on video.js PRs [#2418](https://github.com/videojs/video.js/pull/2418) and [#2420](https://github.com/videojs/video.js/pull/2420).

**Comment by forbesjo** [comment]
I think we should make a dist branch for this too.

**Comment by forbesjo** [comment]
Bumped up the video.js version since those two PR's got merged.

**Comment by simshanith** [comment]
Any idea when this will be available?

**Comment by gkatsev** [comment]
We probably should just release these. I'll work on that this week.

**Comment by simshanith** [comment]
Thanks @gkatsev - able to use this branch via bower currently, but would be nicer if it were an official release. Appreciate it a lot!

**Pull request closed without merging**
